name: Monocleproject
favicon: null
layout_spectrum: 0.64228
typography_spectrum: 0.81888
title: Husband and Wife Photography Team
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c6d6ec'
    - '#5b4f4b'
    - '#2c2727'
    - '#0c6c6d'
    - '#98867d'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
