name: Monocleproject
favicon: null
layout_spectrum: 0.8039742
typography_spectrum: 0.2046187
title: Husband and Wife Photography Team
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#65301E'
    - '#A3A288'
    - '#FFF2CF'
    - '#166590'
    - '#4291DE'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
purpose: []
